---
name: "WGA confluent segmentation"
input_channels: 3
output_channels: 5
CytosolSegmentationCellpose:
    chunk_size: 50 # chunk size for chunked HDF5 storage. is needed for correct caching and high performance reading. should be left at 50.
    cache: "."
    combine_cytosol_channels: [1, 2]
    nucleus_segmentation:
        model: "nuclei"
    cytosol_segmentation:
        model: "cyto2"
    chunk_size: 50
    match_masks: True
    filtering_threshold_mask_matching: 0.95
    filter_masks_size: False
ShardedCytosolSegmentationCellpose:
    shard_size: 12000000 # maxmimum number of pixel per tile
    overlap_px: 100
    nGPUs: 1
    chunk_size: 50 # chunk size for chunked HDF5 storage. is needed for correct caching and high performance reading. should be left at 50.
    threads: 1 # number of shards / tiles segmented at the same size. should be adapted to the maximum amount allowed by memory.
    cache: "."
    combine_cytosol_channels: [1, 2]
    nucleus_segmentation:
        model: "nuclei"
    cytosol_segmentation:
        model: "cyto2"
    chunk_size: 50
    match_masks: True
    filtering_threshold_mask_matching: 0.95
    filter_masks_size: False
HDF5CellExtraction:
    threads: 80 # threads used in multithreading
    image_size: 128 # image size in pixel
    cache: "."
ConvNeXtFeaturizer:
    batch_size: 900
    dataloader_worker_number: 10 #needs to be 0 if using cpu
    inference_device: "auto"
    label: "ConvNeXtFeaturizer"
    channel_selection: 4
MLClusterClassifier:
    batch_size: 900
    inference_device: "cpu"
    dataloader_worker_number: 10 #needs to be 0 if using cpu
    network: "autophagy_classifier"
    label: "Autophagy_15h_classifier2_1"
    encoders: ["forward"]
    channel_selection: 4
CellFeaturizer:
    batch_size: 900
    dataloader_worker_number: 10 #needs to be 0 if using cpu
    inference_device: "cpu"
    label: "CellFeaturizer"