---
name: "Cellpose Segmentation"
CytosolSegmentationCellpose:
    chunk_size: 50 # chunk size for chunked HDF5 storage. is needed for correct caching and high performance reading. should be left at 50.
    cache: "."
    nucleus_segmentation:
        model: "nuclei"
    cytosol_segmentation:
        model: "cyto2"
    match_masks: True
    filtering_threshold_mask_matching: 0.95
    filter_masks_size: False
ShardedCytosolSegmentationCellpose:
    shard_size: 120000000 # maxmimum number of pixel per tile
    overlap_px: 100
    nGPUs: 1
    threads: 1 # number of shards / tiles segmented at the same size. should be adapted to the maximum amount allowed by memory.
    cache: "."
    nucleus_segmentation:
        model: "nuclei"
    cytosol_segmentation:
        model: "cyto2"
    chunk_size: 50
    match_masks: True
    filtering_threshold_mask_matching: 0.95
    filter_masks_size: False
HDF5CellExtraction:
    threads: 80 # threads used in multithreading
    image_size: 400 # image size in pixel
    normalization_range: None #turn of percentile normalization for cells -> otherwise normalise out differences for the alexa647 channel
    cache: "."
CellFeaturizer:
    batch_size: 900
    dataloader_worker_number: 10 #needs to be 0 if using cpu
    inference_device: "auto"
    label: "CellFeaturizer"
LMDSelection:
    processes: 20
    segmentation_channel: 0
    shape_dilation: 16
    smoothing_filter_size: 25
    poly_compression_factor: 30
    path_optimization: "hilbert"
    greedy_k: 15
    hilbert_p: 7
