---
CytosolSegmentationCellpose:
    cache: "."
    nucleus_segmentation:
        model: "nuclei"
    cytosol_segmentation:
        model: "cyto2"
CytosolSegmentationDownsamplingCellpose:
    cache: "."
    downsampling_factor: 2
    nucleus_segmentation:
        model: "nuclei"
    cytosol_segmentation:
        model: "cyto2"
ShardedCytosolSegmentationDownsamplingCellpose:
    downsampling_factor: 2
    shard_size: 120000000 # maxmimum number of pixel per tile
    overlap_px: 100
    nGPUs: 1
    threads: 2 # number of shards / tiles segmented at the same size. should be adapted to the maximum amount allowed by memory.
    cache: "."
    nucleus_segmentation:
        model: "nuclei"
    cytosol_segmentation:
        model: "cyto2"
HDF5CellExtraction:
    threads: 80 # threads used in multithreading
    image_size: 110 # image size in pixel
    cache: "."
CellFeaturizer:
    batch_size: 900
    dataloader_worker_number: 0 #needs to be 0 if using cpu
    inference_device: "cpu"
LMDSelection:
    processes: 20
    segmentation_channel: 0
    shape_dilation: 16
    smoothing_filter_size: 25
    poly_compression_factor: 30
    path_optimization: "hilbert"
    greedy_k: 15
    hilbert_p: 7
